# Generated by Django 4.2.1 on 2023-07-23 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttype',
            old_name='title_de',
            new_name='title_ru',
        ),
    ]
