# Generated by Django 4.2.1 on 2023-08-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_rename_title_de_paymenttype_title_ru"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="cost",
            field=models.PositiveIntegerField(verbose_name="Cost"),
        ),
    ]
