# Generated by Django 4.2.1 on 2023-10-05 06:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address_link',
            field=models.CharField(default=1, max_length=256, verbose_name='Address link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='working_hours',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Working hours'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='working_hours_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Working hours'),
        ),
        migrations.AddField(
            model_name='store',
            name='working_hours_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Working hours'),
        ),
        migrations.AddField(
            model_name='store',
            name='working_hours_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Working hours'),
        ),
    ]
