# Generated by Django 4.2.1 on 2023-07-23 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description_de',
            new_name='description_ru',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title_de',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='title_de',
            new_name='title_ru',
        ),
    ]
