# Generated by Django 4.2.3 on 2023-08-09 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='title_uz',
        ),
    ]
