# Generated by Django 4.2.1 on 2023-10-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_address_link_store_working_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='working_hours_two',
            field=models.CharField(default=1, max_length=256, verbose_name='Working hours'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='working_hours_two_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Working hours'),
        ),
        migrations.AddField(
            model_name='store',
            name='working_hours_two_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Working hours'),
        ),
        migrations.AddField(
            model_name='store',
            name='working_hours_two_uz',
            field=models.CharField(max_length=256, null=True, verbose_name='Working hours'),
        ),
        migrations.AlterField(
            model_name='store',
            name='working_hours',
            field=models.CharField(max_length=256, verbose_name='Working hours'),
        ),
        migrations.AlterField(
            model_name='store',
            name='working_hours_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Working hours'),
        ),
        migrations.AlterField(
            model_name='store',
            name='working_hours_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Working hours'),
        ),
        migrations.AlterField(
            model_name='store',
            name='working_hours_uz',
            field=models.CharField(max_length=256, null=True, verbose_name='Working hours'),
        ),
    ]
