# Generated by Django 4.2.1 on 2023-08-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_collection_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description_2',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
