# Generated by Django 4.2.1 on 2023-08-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_collection_description_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='videos/store/articuls/%Y/%m/%d', verbose_name='Photo'),
        ),
    ]
