# Generated by Django 4.2.1 on 2023-08-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_video_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/store/articuls/%Y/%m/%d', verbose_name='Video file'),
        ),
    ]
