# Generated by Django 4.2.1 on 2023-08-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description_2_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description 2'),
        ),
        migrations.AddField(
            model_name='collection',
            name='description_2_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description 2'),
        ),
        migrations.AddField(
            model_name='collection',
            name='description_2_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Description 2'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description_2',
            field=models.TextField(blank=True, null=True, verbose_name='Description 2'),
        ),
    ]
