# Generated by Django 4.2.1 on 2023-08-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_collection_description_2_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='location',
            field=models.TextField(blank=True, null=True, verbose_name='Location for iFrame'),
        ),
    ]
