# Generated by Django 4.2.1 on 2023-09-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_store_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Info about the store'),
        ),
        migrations.AddField(
            model_name='store',
            name='is_certified',
            field=models.BooleanField(default=True, verbose_name='Is certified'),
        ),
        migrations.AddField(
            model_name='store',
            name='photo',
            field=models.ImageField(default=0, upload_to='images/store/stores/', verbose_name='Store photo'),
            preserve_default=False,
        ),
    ]
