# Generated by Django 4.2.1 on 2023-09-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_store_info_store_is_certified_store_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_header',
            field=models.BooleanField(default=False, verbose_name='Use for header?'),
        ),
    ]
