# Generated by Django 4.2.1 on 2023-09-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_collection_is_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_main_page',
            field=models.BooleanField(default=False, verbose_name='Use for main page?'),
        ),
    ]
