# Generated by Django 4.2.1 on 2023-09-28 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_collection_is_main_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Store page', 'verbose_name_plural': 'Stores page'},
        ),
    ]
