# Generated by Django 4.2.1 on 2023-09-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_header',
            field=models.BooleanField(default=False, verbose_name='Use for header?'),
        ),
    ]
