# Generated by Django 4.2.1 on 2023-07-23 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='content_de',
            new_name='content_ru',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='subtitle_de',
            new_name='subtitle_ru',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title_de',
            new_name='title_ru',
        ),
    ]
