# Generated by Django 4.2.1 on 2023-09-23 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_store_location'),
        ('cart', '0004_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='articul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.articul', verbose_name='Articul'),
        ),
    ]
