# Generated by Django 4.2.1 on 2023-09-29 09:40

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=128, verbose_name='Region')),
                ('region_ru', models.CharField(max_length=128, null=True, verbose_name='Region')),
                ('region_en', models.CharField(max_length=128, null=True, verbose_name='Region')),
                ('region_uz', models.CharField(max_length=128, null=True, verbose_name='Region')),
                ('district', models.CharField(max_length=128, verbose_name='District')),
                ('district_ru', models.CharField(max_length=128, null=True, verbose_name='District')),
                ('district_en', models.CharField(max_length=128, null=True, verbose_name='District')),
                ('district_uz', models.CharField(max_length=128, null=True, verbose_name='District')),
                ('street', models.CharField(max_length=128, verbose_name='Street')),
                ('street_ru', models.CharField(max_length=128, null=True, verbose_name='Street')),
                ('street_en', models.CharField(max_length=128, null=True, verbose_name='Street')),
                ('street_uz', models.CharField(max_length=128, null=True, verbose_name='Street')),
                ('house_no', models.CharField(max_length=12, verbose_name='House number')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='CompanyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='Year')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Company history (About Fabric)',
                'verbose_name_plural': 'Company histories (About Fabric)',
            },
        ),
        migrations.CreateModel(
            name='CompanyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='images/about/company_stats/', verbose_name='Stat icon')),
                ('title', models.CharField(max_length=256, verbose_name='Stat title')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Company stat',
                'verbose_name_plural': 'Company stats',
            },
        ),
        migrations.CreateModel(
            name='ContactPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('phonenumbers', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
            ],
            options={
                'verbose_name': 'Contact number for page',
                'verbose_name_plural': 'Contact numbers for page',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Phone number')),
            ],
            options={
                'verbose_name': 'Phone number',
                'verbose_name_plural': 'Phone numbers',
            },
        ),
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/about/showroom/%Y/%m/%d', verbose_name='Video file')),
                ('stats', models.ManyToManyField(to='about.companystat', verbose_name='Stats')),
            ],
            options={
                'verbose_name': 'Showroom page',
                'verbose_name_plural': 'Showrooms page',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media', models.CharField(max_length=128, verbose_name='Social Media')),
                ('link', models.URLField(verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Medias',
            },
        ),
        migrations.CreateModel(
            name='ShowroomDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('photo', models.ImageField(upload_to='images/about/showroom/%Y/%m/%d', verbose_name='Photo')),
                ('photo_two', models.ImageField(upload_to='images/about/showroom/%Y/%m/%d', verbose_name='Photo')),
                ('showroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details', to='about.showroom', verbose_name='Showroom')),
            ],
            options={
                'verbose_name': 'Showroom Detail',
                'verbose_name_plural': 'Showrooms Detail',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('company_name', models.CharField(max_length=256, verbose_name='Company name')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('address', ckeditor.fields.RichTextField(verbose_name='Address')),
                ('location', models.TextField(blank=True, null=True, verbose_name='Location for iFrame')),
                ('phonenumbers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='about.contactphonenumber', verbose_name='Phone Number')),
                ('social_media', models.ManyToManyField(blank=True, null=True, to='about.socialmedia', verbose_name='Social Media')),
            ],
            options={
                'verbose_name': 'Contact page',
                'verbose_name_plural': 'Contacts page',
            },
        ),
    ]
