# Generated by Django 4.2.1 on 2023-09-29 05:25

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/about/showroom/%Y/%m/%d', verbose_name='Video file')),
                ('stats', models.ManyToManyField(to='about.companystat', verbose_name='Stats')),
            ],
            options={
                'verbose_name': 'Showroom page',
                'verbose_name_plural': 'Showrooms page',
            },
        ),
        migrations.CreateModel(
            name='ShowroomDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('photo', models.ImageField(upload_to='images/about/showroom/%Y/%m/%d', verbose_name='Photo')),
                ('photo_two', models.ImageField(upload_to='images/about/showroom/%Y/%m/%d', verbose_name='Photo')),
                ('showroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details', to='about.showroom', verbose_name='Showroom')),
            ],
            options={
                'verbose_name': 'Showroom Detail',
                'verbose_name_plural': 'Showrooms Detail',
            },
        ),
    ]
