# Generated by Django 4.2.1 on 2023-07-23 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='district_de',
            new_name='district_ru',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='region_de',
            new_name='region_ru',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='street_de',
            new_name='street_ru',
        ),
    ]
