# Generated by Django 4.2.1 on 2023-10-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_link',
            field=models.CharField(default=1, max_length=256, verbose_name='Address link'),
            preserve_default=False,
        ),
    ]
