# Generated by Django 4.2.1 on 2023-10-03 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_contact_company_name_alter_contact_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showroomdetails',
            old_name='photo',
            new_name='images',
        ),
        migrations.RemoveField(
            model_name='showroomdetails',
            name='photo_two',
        ),
    ]
