# Generated by Django 4.2.1 on 2023-09-29 06:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_showroom_showroomdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='type',
        ),
        migrations.AddField(
            model_name='contact',
            name='company_name',
            field=models.CharField(default=1, max_length=256, verbose_name='Company name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='description',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=ckeditor.fields.RichTextField(verbose_name='Address'),
        ),
    ]
