# Generated by Django 4.2.1 on 2023-10-03 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_rename_photo_showroomdetails_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactphonenumber',
            old_name='phonenumbers',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='showroomdetails',
            name='images',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/about/showroom/%Y/%m/%d')),
                ('showroomDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='about.showroomdetails')),
            ],
        ),
    ]
