# Generated by Django 4.2.1 on 2023-09-28 06:56

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_address_house_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('phonenumbers', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
            ],
            options={
                'verbose_name': 'Contact number',
                'verbose_name_plural': 'Contact numbers',
            },
        ),
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/about/showroom/%Y/%m/%d', verbose_name='Video file')),
                ('stats', models.ManyToManyField(to='about.companystat', verbose_name='Stats')),
            ],
            options={
                'verbose_name': 'Showroom page',
                'verbose_name_plural': 'Showrooms page',
            },
        ),
        migrations.AlterModelOptions(
            name='companyhistory',
            options={'verbose_name': 'Company history (About Fabric)', 'verbose_name_plural': 'Company histories (About Fabric)'},
        ),
        migrations.CreateModel(
            name='ShowroomDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('photo', models.ImageField(upload_to='images/about/showroom/%Y/%m/%d', verbose_name='Photo')),
                ('showroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details', to='about.showroom', verbose_name='Showroom')),
            ],
            options={
                'verbose_name': 'Showroom Detail',
                'verbose_name_plural': 'Showrooms Detail',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256, verbose_name='Type')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('address', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('location', models.TextField(blank=True, null=True, verbose_name='Location for iFrame')),
                ('phonenumbers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='about.contactphonenumber', verbose_name='Phone Number')),
                ('social_media', models.ManyToManyField(blank=True, null=True, to='about.socialmedia', verbose_name='Social Media')),
            ],
            options={
                'verbose_name': 'Contact page',
                'verbose_name_plural': 'Contacts page',
            },
        ),
    ]
