# Generated by Django 4.2.1 on 2023-10-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_rename_phonenumbers_contactphonenumber_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.RemoveField(
            model_name='image',
            name='showroomDetails',
        ),
        migrations.AddField(
            model_name='contact',
            name='address_link',
            field=models.CharField(default=1, max_length=256, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='showroomdetails',
            name='images',
            field=models.ManyToManyField(blank=True, to='about.image', verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/about/showroom/%Y/%m/%d', verbose_name='Image'),
        ),
    ]
