# Generated by Django 4.2.1 on 2023-09-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_contactphonenumber_showroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='showroomdetails',
            name='photo_two',
            field=models.ImageField(default=1, upload_to='images/about/showroom/%Y/%m/%d', verbose_name='Photo'),
            preserve_default=False,
        ),
    ]
