# Generated by Django 4.2.1 on 2023-10-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_image_options_remove_image_showroomdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default=1, max_length=256, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
