# Generated by Django 4.2.1 on 2023-09-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_showroomdetails_photo_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showroomdetails',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
    ]
