# Generated by Django 4.2.1 on 2023-10-03 07:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_image_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyStatForShowroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='images/about/company_stats/', verbose_name='Stat icon')),
                ('title', models.CharField(max_length=256, verbose_name='Stat title')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Company stat for showroom',
                'verbose_name_plural': 'Company stats for showroom',
            },
        ),
        migrations.AlterField(
            model_name='showroom',
            name='stats',
            field=models.ManyToManyField(to='about.companystatforshowroom', verbose_name='Stats'),
        ),
    ]
