# Generated by Django 4.2.1 on 2023-10-03 07:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_companystatforshowroom_alter_showroom_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyhistory',
            name='content',
        ),
        migrations.AddField(
            model_name='companyhistory',
            name='description',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyhistory',
            name='description_two',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Description two'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyhistory',
            name='image',
            field=models.ImageField(default=1, upload_to='images/about/company_history/', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyhistory',
            name='image_two',
            field=models.ImageField(default=1, upload_to='images/about/company_history/', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
