# Generated by Django 4.2.1 on 2023-10-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_remove_companyhistory_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address_link',
            field=models.CharField(max_length=256, verbose_name='Address link'),
        ),
    ]
