# Generated by Django 4.2.1 on 2023-08-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_collection_title_en_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='liked_products',
            field=models.ManyToManyField(blank=True, related_name='liked_users', to='store.collection', verbose_name='Liked collections'),
        ),
    ]
